export const users = [
    {
        email: 'سارینا.کوتی@example.com',
        gender: 'female',
        phone_number: '0997-267-1133',
        birthdate: 1077518239,
        location: {
            street: '5273 سمیه',
            city: 'بیرجند',
            state: 'تهران',
            postcode: 99854,
        },
        username: 'yellowpeacock139',
        password: 'chopper',
        first_name: 'سارینا',
        last_name: 'کوتی',
        title: 'mrs',
        picture: 'women/38.jpg',
    },
    {
        email: 'melissa.fleming@example.com',
        gender: 'female',
        phone_number: '0740-304-475',
        birthdate: 469521368,
        location: {
            street: '3655 manchester road',
            city: 'winchester',
            state: 'berkshire',
            postcode: 'YB2 8EJ',
        },
        username: 'goldenkoala410',
        password: 'sick',
        first_name: 'melissa',
        last_name: 'fleming',
        title: 'miss',
        picture: 'algolia/women/pragati.png',
    },
    {
        email: 'christoffer.christiansen@example.com',
        gender: 'male',
        phone_number: '05761325',
        birthdate: 244475798,
        location: {
            street: '3391 pilevangen',
            city: 'overby lyng',
            state: 'danmark',
            postcode: 88520,
        },
        username: 'smallbird985',
        password: 'samuel',
        first_name: 'christoffer',
        last_name: 'christiansen',
        title: 'mr',
        picture: 'algolia/men/lucas.png',
    },
    {
        email: 'valtteri.pulkkinen@example.com',
        gender: 'male',
        phone_number: '041-829-79-61',
        birthdate: 9608479,
        location: {
            street: '6489 hermiankatu',
            city: 'parikkala',
            state: 'northern savonia',
            postcode: 77761,
        },
        username: 'brownfish540',
        password: 'peepee',
        first_name: 'valtteri',
        last_name: 'pulkkinen',
        title: 'mr',
        picture: 'men/49.jpg',
    },
    {
        email: 'todd.beck@example.com',
        gender: 'male',
        phone_number: '0768-374-878',
        birthdate: 216450355,
        location: {
            street: '7846 chester road',
            city: 'wakefield',
            state: 'shropshire',
            postcode: 'U43 3QT',
        },
        username: 'bigelephant503',
        password: 'rrrrr',
        first_name: 'todd',
        last_name: 'beck',
        title: 'mr',
        picture: 'men/65.jpg',
    },
    {
        email: 'kayla.hall@example.com',
        gender: 'female',
        phone_number: '(932)-142-5202',
        birthdate: 450297969,
        location: {
            street: '1935 aldwins road',
            city: 'whangarei',
            state: 'gisborne',
            postcode: 22546,
        },
        username: 'beautifulkoala361',
        password: 'lickit',
        first_name: 'kayla',
        last_name: 'hall',
        title: 'ms',
        picture: 'women/32.jpg',
    },
    {
        email: 'jimmie.simmons@example.com',
        gender: 'male',
        phone_number: '0702-239-646',
        birthdate: 691663054,
        location: {
            street: '1790 the grove',
            city: 'bangor',
            state: 'isle of wight',
            postcode: 'D0 5PJ',
        },
        username: 'silverelephant404',
        password: 'stang',
        first_name: 'jimmie',
        last_name: 'simmons',
        title: 'mr',
        picture: 'men/25.jpg',
    },
    {
        email: 'benedikt.hein@example.com',
        gender: 'male',
        phone_number: '0170-2625830',
        birthdate: 233934049,
        location: {
            street: '5245 kirchstraße',
            city: 'börde',
            state: 'hessen',
            postcode: 99021,
        },
        username: 'goldenelephant510',
        password: 'katie1',
        first_name: 'benedikt',
        last_name: 'hein',
        title: 'mr',
        picture: 'men/56.jpg',
    },
    {
        email: 'aloïs.moulin@example.com',
        gender: 'male',
        phone_number: '(334)-138-2260',
        birthdate: 787209800,
        location: {
            street: '6574 rue cyrus-hugues',
            city: 'berolle',
            state: 'genève',
            postcode: 8691,
        },
        username: 'silvergorilla196',
        password: 'silver',
        first_name: 'aloïs',
        last_name: 'moulin',
        title: 'monsieur',
        picture: 'men/28.jpg',
    },
    {
        email: 'noah.smith@example.com',
        gender: 'male',
        phone_number: '314-264-1915',
        birthdate: 546423933,
        location: {
            street: '8380 st. lawrence ave',
            city: 'inverness',
            state: 'nova scotia',
            postcode: 24765,
        },
        username: 'biggorilla322',
        password: 'kane',
        first_name: 'noah',
        last_name: 'smith',
        title: 'mr',
        picture: 'men/20.jpg',
    },
    {
        email: 'noah.dupont@example.com',
        gender: 'male',
        phone_number: '(280)-900-0140',
        birthdate: 857793035,
        location: {
            street: '1372 rue de bonnel',
            city: 'vucherens',
            state: 'zürich',
            postcode: 5466,
        },
        username: 'redbear614',
        password: 'adidas',
        first_name: 'noah',
        last_name: 'dupont',
        title: 'monsieur',
        picture: 'men/52.jpg',
    },
    {
        email: 'necati.nalbantoğlu@example.com',
        gender: 'male',
        phone_number: '(566)-322-5199',
        birthdate: 1431069936,
        location: {
            street: '5253 istiklal cd',
            city: 'şırnak',
            state: 'samsun',
            postcode: 88399,
        },
        username: 'yellowduck640',
        password: 'deborah',
        first_name: 'necati',
        last_name: 'nalbantoğlu',
        title: 'mr',
        picture: 'men/17.jpg',
    },
];
